<?php

namespace App\Constants;

/**
 * The documents the Act and the Rules call for alongside a service form.
 *
 * Two questions decide every entry here, and they are answered from the provisions rather than from
 * the printed form, because the printed form only ever says "List of enclosures:" with two blank
 * numbered lines.
 *
 * **Is the document named?** Only twice. Rule 13(3) names "the certified copy of the order of the
 * Rent Court appealed against" on Form VI, and paragraph 5 of Forms II to VI names "the decisions
 * of such cases" where a prior proceeding has been disposed of. Everything else the instruments say
 * is unnamed: "relevant document and available evidence" (rule 7), "affidavit and documents, if
 * any" (Act s. 35(1)(a)), "affidavits and documents, if any" (rule 11(1)).
 *
 * **Is it required?** Only where the provision makes the filing conditional on it. Rule 13(3) says
 * "shall be accompanied by", and Act s. 37(1) independently says the appeal is preferred "along
 * with a certified copy of such order" - so on Form VI that document is a condition of the appeal.
 * Paragraph 5's decisions are required conditionally: the obligation arises only if the filer
 * discloses a disposed case. Every "if any" is optional, and the audit of 7 September 2026 already
 * fixed that reading for these forms - see docs/statutory-forms-engine-plan.md §3.11.
 *
 * A named entry that is not required is still worth naming: it gives the filer a labelled slot
 * instead of a blank list, and it records which provision expects the document. It does not gate
 * submission.
 *
 * Labels are snapshotted onto each row for the same reason declaration text is - see
 * App\Constants\Declarations. Mirrored in frontend/src/constants/enclosures.js, and
 * tests/Unit/EnclosuresTest.php fails if the two copies drift.
 */
class Enclosures
{
    /** Anything the filer attaches that no provision names. */
    public const OTHER = 'other';

    /** Rule 13(3) and Act s. 37(1). The one enclosure that gates a filing. */
    public const FORM_VI_CERTIFIED_ORDER = 'form_vi.certified_order';

    /** Rule 13(3), second limb: "such other documents as may be required to support grounds". */
    public const FORM_VI_GROUNDS_SUPPORT = 'form_vi.grounds_support';

    /** Act s. 35(1)(a). Form V's paragraph 1 describes an order; this is that order. */
    public const FORM_V_ORDER_COPY = 'form_v.order_copy';

    /** Rule 7: "along with relevant document and available evidence". */
    public const FORM_II_EVIDENCE = 'form_ii.evidence';

    /** Rule 11(1): "accompanied by affidavits and documents, if any". */
    public const FORM_IV_AFFIDAVIT = 'form_iv.affidavit';

    /** Rule 5(4): Form I-B may only follow an order fixing rent under rule 5(3). */
    public const FORM_IB_PARENT_ORDER = 'form_i_b.parent_order';

    /** Paragraph 5, Forms II to VI: "the decisions of such cases to be enclosed". */
    public const PRIOR_PROCEEDING_DECISION = 'prior_proceeding.decision';

    /**
     * Prescribed slots per form. Anything not listed is filed as OTHER.
     *
     * PRIOR_PROCEEDING_DECISION is deliberately absent: it is not one slot but one per disposed
     * entry the filer discloses, so it is generated by App\Support\Enclosures from the paragraph 5
     * answers rather than declared here.
     */
    private const PRESCRIBED = [
        ApplicationTypes::VALUER_APPOINTMENT => [
            [
                'kind' => self::FORM_IB_PARENT_ORDER,
                'label' => 'Order of the Rent Authority fixing the rent or other charges',
                'required' => false,
                'provision_refs' => ['rules.5(4)', 'rules.5(3)'],
                'note' => 'Rule 5(4) allows this application only where the applicant does not agree with the rent or other charges already fixed under rule 5(3).',
            ],
        ],
        ApplicationTypes::RENT_COURT_POSSESSION => [
            [
                'kind' => self::FORM_II_EVIDENCE,
                'label' => 'Relevant documents and available evidence',
                'required' => false,
                'provision_refs' => ['rules.7', 'act.35(1)(a)'],
                'note' => 'Rule 7 has the application made "along with relevant document and available evidence".',
            ],
        ],
        ApplicationTypes::RENT_AUTHORITY_FILING => [
            [
                'kind' => self::FORM_IV_AFFIDAVIT,
                'label' => 'Affidavit in support of the application',
                'required' => false,
                'provision_refs' => ['rules.11(1)', 'act.35(1)(a)'],
                'note' => 'Rule 11(1): the application is made "accompanied by affidavits and documents, if any".',
            ],
        ],
        ApplicationTypes::RENT_COURT_APPEAL => [
            [
                'kind' => self::FORM_V_ORDER_COPY,
                'label' => 'Copy of the order of the Rent Authority appealed against',
                'required' => false,
                'provision_refs' => ['act.35(1)(a)', 'act.32(1)'],
                'note' => 'Paragraph 1 describes the order appealed against. Unlike rule 13(3) for the Tribunal, no rule requires a certified copy for an appeal to the Rent Court.',
            ],
        ],
        ApplicationTypes::RENT_TRIBUNAL_APPEAL => [
            [
                'kind' => self::FORM_VI_CERTIFIED_ORDER,
                'label' => 'Certified copy of the order of the Rent Court appealed against',
                'required' => true,
                'provision_refs' => ['rules.13(3)', 'act.37(1)'],
                'note' => 'Rule 13(3): each Memorandum "shall be accompanied by" it. Act s. 37(1) has the appeal preferred "along with a certified copy of such order".',
            ],
            [
                'kind' => self::FORM_VI_GROUNDS_SUPPORT,
                'label' => 'Documents supporting the grounds of objection in the Memorandum',
                'required' => false,
                'provision_refs' => ['rules.13(3)'],
                'note' => 'Rule 13(3), second limb: "such other documents as may be required to support grounds of objection mentioned in the Memorandum".',
            ],
        ],
    ];

    /** The label written on a paragraph 5 decision, with the case it belongs to. */
    public static function priorProceedingLabel(string $caseNumber, string $forum): string
    {
        return sprintf('Decision in %s before %s', $caseNumber, $forum);
    }

    public const PRIOR_PROCEEDING_PROVISIONS = ['rules.schedule.form_ii_to_vi.para_5'];

    /** The prescribed slots for a form, in the order they should be shown. */
    public static function forForm(string $applicationType): array
    {
        return self::PRESCRIBED[$applicationType] ?? [];
    }

    /** Slots the filer cannot submit without. */
    public static function requiredFor(string $applicationType): array
    {
        return array_values(array_filter(
            self::forForm($applicationType),
            static fn (array $slot) => $slot['required'] === true
        ));
    }

    public static function definition(string $applicationType, string $kind): ?array
    {
        foreach (self::forForm($applicationType) as $slot) {
            if ($slot['kind'] === $kind) {
                return $slot;
            }
        }

        return null;
    }

    /** Every kind a given form will accept. */
    public static function kindsFor(string $applicationType): array
    {
        $kinds = array_column(self::forForm($applicationType), 'kind');
        $kinds[] = self::PRIOR_PROCEEDING_DECISION;
        $kinds[] = self::OTHER;

        return $kinds;
    }

    /** Every form that declares prescribed slots, for tests and tooling. */
    public static function forms(): array
    {
        return array_keys(self::PRESCRIBED);
    }
}
